doctrine:
  dbal:
    default_connection: data
    connections:
      data:
        driver: pdo_pgsql
        server_version: '16'
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          ltree: string
  orm:
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      Carting:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Carting\Entity'
        alias: Carting
      ObjectingEmbeddable:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
        prefix: 'App\Objecting\Embeddable'
        alias: Objecting
