services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Carting\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/DependencyInjection/'
      - '../src/Contract/'
      - '../src/DTO/'
      - '../src/Snapshot/'
  App\Carting\ServiceInterface\CartOfferProviderInterface:
    alias: App\Carting\Provider\CartUnavailableOfferProvider
  App\Carting\RepositoryInterface\CartRepositoryInterface:
    alias: App\Carting\Repository\CartRepository
  App\Carting\RepositoryInterface\CartCheckoutHandoffRepositoryInterface:
    alias: App\Carting\Repository\CartCheckoutHandoffRepository
